<template>
    <div  class="home pa-10">
        <h1>O Kudrnovi</h1>
        <h3 class="big black-text">Jak to doopravdicky bylo s našim Kudrnou a jeho kolomaznickým rodem</h3>
        <h4>To je histórie dlouhá jako lidstvo samo.</h4>
        <p>Jelikož v písemných materiálech těch největších stěhovavých národů při počátku našeho letopočtu jsme žádnou zmínku o tomto rodu Kudrnů nenašli (stěhovavých proto, že cestování musel mít jejich rod nutně v krvi), usuzujeme že jejich dávní a slavní předkové byly Keltové, neboť tito z důvodů utajení vůbec nepsali, ale moudrosti si předávali z hlavy do hlavy (z palice do palice). Při archeologickém průzkumu moravského keltského oppida Staré Hradisko byly ale pozůstatky kolomazných pecí nalezeny. Takže pro toto se při svých výzkumech kudrnologové i tolik zaměřují na vše o Keltech.</p>
        <h4>Další kapitolkou je kolomaznictví.</h4>
        <p>Kolomaz je produkt, vznikající suchou destilací dřeva v kolomazných pecích, milířích, ... Dá se v horších formách získat v udírnách, zákoutích kamen se špatným spalováním a vůbec. I toto by bylo dlouhé povídání. Do našeho patronátního archeologického skanzenu Villa Nova v Uhřínově můžete všichni přijet a vše si zkusit připravit a vyrobit sami. Že ale není Kolomaz jako Kolomaz dokazuje věhlas Kudrnů. Tito nejslavnější v kolomaznické branži věděli co do své černé mazlaviny přidat, aby obstála při snížení tření těch nejrozličnějších ploch. Jiná byla u selských vozů kde “šlo dřevo na dřevo”, jiná u panských kočárů, kde již byla zkoušena opouzdřená ložiska (zde si například Kudrna vypomáhal husím sádlem) a zouplna jiná pro to ... fšak víte. Máme zprávy že Kudrnové kolomazí i léčili ... např. kulhavku u dobytků, ... jsou nezřídké zprávy jak vhodným přiložením pomohli i lidem.</p>
        <h4>Trakař a další</h4>
        <p>Jediným dopravním prostředkem Kudrnů býval odjakživa trakař = vozidlo jehož vývoj též silně ovlivnili. Znám je jejich vynález rameních popruhů, čímž odlehčili paže,... dále pak nahrazení kolečka při sněhu lyží či vodní úprava - kdy se trakař mění v řiditelné plavidlo. Jen sen o létajícím trakaři se zatím nepodařilo zrealizovat.
        Slamák (ten si půjčil do image i Jiří Suchý), ušatá bečička a barvy zelená se žlutou byly další neodmyslitelné poznávací znaky našeho MISTRA.</p>
        <h4>Mistr</h4>
        <p>Nás ale nejvíc zajímá přímo tento MISTR - “náš” Jan “Žanek” Kudrna, oficiálně poslední z tohoto nejstaršího kolomaznického rodu vyznačujícím se i NADPRŮMĚRNOU DLOUHOVĚKOSTÍ. Narodil se jako jediný syn v domku, kde Kudrnové odjakživa sídlili - kousek východně od Brna v Mariánském údolí (pod vesničkou Líšeň) 9.9.1833 tátovi Janovi (*1807) a mamince Anežce (*1811). V jejich kolomaznické osadě ještě stále žili i stařešinové rodu ... dědeček Jan (*1779) s babičkou Boženkó (*1786). Náš “Žaneček” ale v dětství nejraději poslouchal prababičku Marii (*1753), ale hlavně pradědečka Jana (*1750), který se nejvíce proslavil jako gilotinový mazavka při francouzské revoluci 1789. Móc pěkně se jim tam žilo. Žanka velmi romanticky ovlivnila i návštěva Karla Hynka Máchy, který se zastavil i ve své černé - rudě podšité peleríně na jaře 1836, tříletého budoucího dobrodruha pohoupal na kolenou a poklábosili drobátko. U Kudrnů K. H. M. parádně uhasil žízeň (kudrnovic slivovice, přezdívaná i “živá voda” bývala též světoznámá). Máchovo hašení v Litoměřicích o něco později pak dopadlo zouplně neparádně.</p>
        <h4>První zájezd</h4>
        <p>Pro nás je ale nejdůležitější a silně zavazující začátek jeho světoběžnické kariéry. Uspořádal totiž 1.zájezd na světě (ještě dříve než nesprávně uváděný p. Cook z Anglie), když jako osmiletý (v květnu 1841, právě měsíc před tím englickým vy-kůkem) přesvědčil tátu, od mlynáře Vávry půjčili žebřiňák (koníka měli) a za tři krejcary dovezli kamarády na Macochu, kde jim navíc na ohníčku uvařili oběd. Tímto se prokazatelně stal Žanek Kudrna i zakladatelem světového organizovaného cestovního ruchu.V polovině 19. století vzniká i slavná brzy zlidovělá písnička Jede Kudrna okolo Brna (viz. příloha). Ano tak to vždy přesně bylo! Snaha uspokojit klientelu mu byla přednější než namazání vlastního - příšerňácky vrzajícího - kolečka. A pak už to šlo ráz na ráz, veden neomylnou intuicí stával u stěžejních dějinných událostí doma i ve světě. Zde jen pro ilustraci a namátkou pár z jeho zážitků: Svá Kristova léta např. prožil jako rakouský voják po boku kanonýra Jabůrka, aby 3. 7. 1866 naposledy namazal osy jeho kanónu. O dva roky později už maže vozy tahající do Prahy základní kameny na Národní divadlo - byl velkým milovníkem (i divadla). V roce 1888 i spoluzakládal Klub českých turistů (KČT).Při hospodářské krizi odjel do Ameriky - skamarádil se s J. Londonem (posloužil mu jako model pro mnoho neohrožených postav), vyhrál kolomaznickou soutěž na Klondike, . . . . .Ano, dodal i R. Amundsenovi krabičku famózního skluznicového mazadla, aby on pak 15. 12. 1911 dosáhl jako první z lidí jižního pólu. V letadle, kterým letěl R.A. na pomoc trosečníkům ze vzducholodi generála Nobileho, naštěstí nebyl.</p>
        <h4>... prožil na několik svazků životopisu</h4>
        <p>Vážení, kam jen se ve světě hnete - naleznete jeho stopy. Oženit se nestačil! Děcka nějaký sem tam měl, ale víte, jak to u dobrodruhů chodí. Nástup minerálních mazadel a tím pádem nemožnost předat živnost jej tak rozesmutnil, že vůbec necítil potřebu zplodit legitimního syna, jak desítky pokolení před ním, a předat mu řemeslo.</p>
        <h4>Poslední zájezd</h4>
        <p>"Údajně" osudné se mu stalo přátelství s Richardem Halliburtonem, který si jej tak oblíbil, že jej jako 106-ti letého, ale vitálního staříka vzal v březnu 1939 na svojí džunku plující z Hongkongu do Friska. Jednou přestali vysílat a do Friska nedojeli. Údajně zmizeli v Pacifiku. My ale věříme, že dnes KUDRNA i s Ríšó žijí tam na souostroví MIDWAY (severozápadně od Havaje). V rekordním věku 165-ti let užívá zaslouženého odpočinku a zpovzdálí sleduje, jak jeho pokračovatelé z K.C.R. KUDRNA ten jeho uvrzgané tragáč vezóóóó dál.</p>
        
    </div>
</template>

<script>
  export default {
    name: 'Home',
      }
</script>